name: "Size Diff"
description: "Calculates the difference in a file's size, compared to a golden standard (like your main branch)."
author: "Jacob Ras"
branding:
  icon: monitor
  color: orange

inputs:
  path:
    description: "The path of the file to monitor the size of."
    required: true
  main-branch-name:
    description: "The name of your main branch."
    default: "main"
    required: false

outputs:
  summary:
    description: "A readable summary of the file size difference"

runs:
  using: node20
  main: dist/index.js