name: "Size Diff"
description: "Calculates the difference in a file's size, compared to a golden standard (like your main branch)."
author: "Jacob Ras"

inputs:
  path:
    description: "The path of the file to monitor the size of."
    required: true
  diffSize:
    description: "Whether to diff the size or just store it (i.e. whether this is running on the main branch)."
    required: true

outputs:
  summary:
    description: "A readable summary of the file size difference"

runs:
  using: node20
  main: dist/index.js