import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test

class SummaryBuilderTest {

    @Test
    fun increase() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 300,
            newSizeBytes = 400
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 300 bytes
            **📦 New .zip size:** 400 bytes

            🔼 File size **increases by 100 bytes**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun decrease() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 500,
            newSizeBytes = 400
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 500 bytes
            **📦 New .zip size:** 400 bytes

            🔽 File size **decreases by 100 bytes**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun noChange() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 400,
            newSizeBytes = 400
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 400 bytes
            **📦 New .zip size:** 400 bytes

            File size does not change.
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }
}