import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test

class SummaryBuilderTest {

    @Test
    fun increaseKB() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 300,
            newSizeBytes = 400,
            largeFiles = emptyList()
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 300 bytes
            **📦 New .zip size:** 400 bytes

            🔼 File size **increases by 100 bytes**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun increaseMB() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.apk",
            existingSizeBytes = 300,
            newSizeBytes = 4_000_000,
            largeFiles = emptyList()
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .apk size:** 300 bytes
            **📦 New .apk size:** 3.8 MB

            🔼 File size **increases by 3.8 MB**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun increaseGB() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.mkv",
            existingSizeBytes = 300,
            newSizeBytes = 8_000_000_000,
            largeFiles = emptyList()
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .mkv size:** 300 bytes
            **📦 New .mkv size:** 7.5 GB

            🔼 File size **increases by 7.5 GB**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun increaseWithLargeFiles() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 300,
            newSizeBytes = 400,
            largeFiles = listOf(
                FileInfo("app/test.jpg", 999_000)
            )
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 300 bytes
            **📦 New .zip size:** 400 bytes

            🔼 File size **increases by 100 bytes**

            Large files added/modified in this PR:
            * `app/test.jpg`: 976 kB
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun decrease() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 500,
            newSizeBytes = 400,
            largeFiles = emptyList()
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 500 bytes
            **📦 New .zip size:** 400 bytes

            🔽 File size **decreases by 100 bytes**
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }

    @Test
    fun noChange() {
        val summary = SummaryBuilder.buildDiff(
            path = "test.zip",
            existingSizeBytes = 400,
            newSizeBytes = 400,
            largeFiles = emptyList()
        )
        assertThat(summary).isEqualTo(
            """
            **📦 Previous .zip size:** 400 bytes
            **📦 New .zip size:** 400 bytes

            File size does not change.
            
            <sup>_Generated by `jacobras/size-diff-action`_</sup>
        """.trimIndent()
        )
    }
}