[versions]
kotlin = "2.2.0"

[libraries]
humanReadable = { module = "nl.jacobras:Human-Readable", version = "1.12.0" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }