on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Launch test action
        uses: ./
        id: test
        with:
          path: test-*.zip
          main-branch-name: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          large-file-threshold-kb: 100

      - name: Print Output
        run: |
          echo "${{ steps.test.outputs.summary }}"